version: "3"
services:
  db:
    container_name: finance_db
    restart: "on-failure"
    image: mysql:8
    ports:
      - 3030:3306
    env_file:
      - env/.env
    volumes:
      - ./database/mysql:/var/lib/mysql

  backend:
    container_name: finance_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    env_file:
      - env/.env
    depends_on:
      - db
    command: ["/app/start.sh"]

  frontend:
    container_name: finance_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    env_file:
      - env/.env
    depends_on:
      - backend
    command: ["pnpm", "run", "dev"]

  nginx:
    container_name: finance_nginx
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
