version: '3'
services:
  mysql:
    container_name: finance_db
    restart: "on-failure"
    image: mysql:8
    ports:
      - 3306:3306
    env_file:
      - env/.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./database/mysql:/var/lib/mysql
      
  # backend:
  #   container_name: finance_backend
  #   build: 
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8000:8000
  #   volumes:
  #     - .:/app
  #   env_file:
  #     - env/.env
  #   depends_on:
  #     - mysql
  #   command: ["/app/start.sh"]